name: Build and Deploy React App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the public repository
        uses: actions/checkout@v3

      - name: Setup SSH for submodule access
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Checkout the private submodule
        run: |
          git submodule init
          git submodule update --remote --merge
          git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
          cd portfolio/altflutter

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'  # Adjust to your desired Flutter version

      - name: Install Dependencies
        run: cd portfolio/altflutter && flutter pub get

      - name: Build Web
        run: cd portfolio/altflutter && flutter build web --release

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: portfolio/altflutter/build/web

  deploy:
    name: Deploy to GitHub Pages
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
